# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon May 11 19:21:36 2020
#      by: pyside2-uic 2.0.0 running on PySide2 5.6.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ngv_mainwindow(object):
    def setupUi(self, ngv_mainwindow):
        ngv_mainwindow.setObjectName("ngv_mainwindow")
        ngv_mainwindow.resize(965, 731)
        self.centralwidget = QtWidgets.QWidget(ngv_mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.files_tab = QtWidgets.QWidget()
        self.files_tab.setObjectName("files_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.files_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.files_listWidget = QtWidgets.QListWidget(self.files_tab)
        self.files_listWidget.setObjectName("files_listWidget")
        self.verticalLayout.addWidget(self.files_listWidget)
        self.tabWidget.addTab(self.files_tab, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toolBox = QtWidgets.QToolBox(self.widget)
        self.toolBox.setObjectName("toolBox")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 197, 257))
        self.page_3.setObjectName("page_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_autonrow = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_autonrow.setChecked(True)
        self.checkBox_autonrow.setObjectName("checkBox_autonrow")
        self.gridLayout.addWidget(self.checkBox_autonrow, 1, 2, 1, 1)
        self.spinBox_nrow = QtWidgets.QSpinBox(self.page_3)
        self.spinBox_nrow.setEnabled(False)
        self.spinBox_nrow.setMinimum(1)
        self.spinBox_nrow.setProperty("value", 5)
        self.spinBox_nrow.setObjectName("spinBox_nrow")
        self.gridLayout.addWidget(self.spinBox_nrow, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.checkBox_userange = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_userange.setObjectName("checkBox_userange")
        self.gridLayout.addWidget(self.checkBox_userange, 4, 0, 1, 1)
        self.spinBox_drawrange_upper = QtWidgets.QSpinBox(self.page_3)
        self.spinBox_drawrange_upper.setEnabled(False)
        self.spinBox_drawrange_upper.setMinimum(1)
        self.spinBox_drawrange_upper.setMaximum(999)
        self.spinBox_drawrange_upper.setObjectName("spinBox_drawrange_upper")
        self.gridLayout.addWidget(self.spinBox_drawrange_upper, 3, 2, 1, 1)
        self.spinBox_offset = QtWidgets.QSpinBox(self.page_3)
        self.spinBox_offset.setObjectName("spinBox_offset")
        self.gridLayout.addWidget(self.spinBox_offset, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.page_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.page_3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox_offset_2 = QtWidgets.QSpinBox(self.page_3)
        self.spinBox_offset_2.setProperty("value", 1)
        self.spinBox_offset_2.setObjectName("spinBox_offset_2")
        self.gridLayout.addWidget(self.spinBox_offset_2, 2, 1, 1, 1)
        self.spinBox_drawrange_lower = QtWidgets.QSpinBox(self.page_3)
        self.spinBox_drawrange_lower.setEnabled(False)
        self.spinBox_drawrange_lower.setObjectName("spinBox_drawrange_lower")
        self.gridLayout.addWidget(self.spinBox_drawrange_lower, 3, 1, 1, 1)
        self.checkBox_highres = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_highres.setObjectName("checkBox_highres")
        self.gridLayout.addWidget(self.checkBox_highres, 5, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 84, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 147, 46))
        self.page_4.setObjectName("page_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.page_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.page_4)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 0, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 208, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.toolBox.addItem(self.page_4, "")
        self.verticalLayout_2.addWidget(self.toolBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 308, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.tabWidget.addTab(self.widget, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_label.sizePolicy().hasHeightForWidth())
        self.image_label.setSizePolicy(sizePolicy)
        self.image_label.setMinimumSize(QtCore.QSize(720, 0))
        self.image_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.image_label.setText("")
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.horizontalLayout.addWidget(self.image_label)
        ngv_mainwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ngv_mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 965, 21))
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtWidgets.QMenu(self.menubar)
        self.menuFiles.setObjectName("menuFiles")
        ngv_mainwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ngv_mainwindow)
        self.statusbar.setObjectName("statusbar")
        ngv_mainwindow.setStatusBar(self.statusbar)
        self.actionOpen_Folder = QtWidgets.QAction(ngv_mainwindow)
        self.actionOpen_Folder.setObjectName("actionOpen_Folder")
        self.actionOpen_Segmentation_Folder = QtWidgets.QAction(ngv_mainwindow)
        self.actionOpen_Segmentation_Folder.setObjectName("actionOpen_Segmentation_Folder")
        self.actionSave_Configuration = QtWidgets.QAction(ngv_mainwindow)
        self.actionSave_Configuration.setObjectName("actionSave_Configuration")
        self.actionExport_Images = QtWidgets.QAction(ngv_mainwindow)
        self.actionExport_Images.setObjectName("actionExport_Images")
        self.menuFiles.addAction(self.actionOpen_Folder)
        self.menuFiles.addAction(self.actionOpen_Segmentation_Folder)
        self.menuFiles.addAction(self.actionSave_Configuration)
        self.menuFiles.addAction(self.actionExport_Images)
        self.menubar.addAction(self.menuFiles.menuAction())

        self.retranslateUi(ngv_mainwindow)
        self.tabWidget.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ngv_mainwindow)

    def retranslateUi(self, ngv_mainwindow):
        ngv_mainwindow.setWindowTitle(QtWidgets.QApplication.translate("ngv_mainwindow", "NIfTI-gridvew", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.files_tab), QtWidgets.QApplication.translate("ngv_mainwindow", "Files", None, -1))
        self.checkBox_autonrow.setText(QtWidgets.QApplication.translate("ngv_mainwindow", "Auto", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("ngv_mainwindow", "Draw Range:", None, -1))
        self.checkBox_userange.setText(QtWidgets.QApplication.translate("ngv_mainwindow", "Use Range", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("ngv_mainwindow", "Padding:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("ngv_mainwindow", "Nrow:", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("ngv_mainwindow", "Offset:", None, -1))
        self.checkBox_highres.setText(QtWidgets.QApplication.translate("ngv_mainwindow", "High Res", None, -1))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QtWidgets.QApplication.translate("ngv_mainwindow", "General Options", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("ngv_mainwindow", "Colormap: ", None, -1))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), QtWidgets.QApplication.translate("ngv_mainwindow", "Image Options", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), QtWidgets.QApplication.translate("ngv_mainwindow", "Toolbox", None, -1))
        self.menuFiles.setTitle(QtWidgets.QApplication.translate("ngv_mainwindow", "Files", None, -1))
        self.actionOpen_Folder.setText(QtWidgets.QApplication.translate("ngv_mainwindow", "Open Folder", None, -1))
        self.actionOpen_Segmentation_Folder.setText(QtWidgets.QApplication.translate("ngv_mainwindow", "Open Segmentation Folder", None, -1))
        self.actionSave_Configuration.setText(QtWidgets.QApplication.translate("ngv_mainwindow", "Save Configuration", None, -1))
        self.actionExport_Images.setText(QtWidgets.QApplication.translate("ngv_mainwindow", "Export Images...", None, -1))

